reditclone/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


app_name='accounts'
urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logoutview, name='logout'),
    
]

reditclone/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls import url


app_name='posts'
urlpatterns = [
    path('create/',views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote/',views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote/',views.downvote, name='downvote'),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name='userposts'),
    
]

reditclone/reditclone/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    url(r'^$', views.home, name="home"),
]

reditclone/accounts/models.py
from django.db import models

# Create your models here.

reditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User , on_delete=models.DO_NOTHING)
    votes_total = models.IntegerField(default=1)
    
    

reditclone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def signup(request):
    if request.method=='POST':
        if request.POST['Password1']== request.POST['Password2']:
            try:
                user=User.objects.get(username=request.POST['Username'])
                return render(request, 'accounts/signups.html', {'error':'Oops! Username already taken!'})
            except User.DoesNotExist:
                user=User.objects.create_user(request.POST['Username'], password=request.POST['Password1'], )
                login(request, user)
                return render(request, 'accounts/signups.html')
        else:
            return render(request, 'accounts/signups.html', {'error':'Oops! Passwords Don''t match'})
    else:
        return render(request, 'accounts/signups.html')
    
    
def login_user(request):
    if request.method=='POST':
        user=authenticate(username=request.POST['Username'], password=request.POST['Password'])
        if user is not None:
            login(request, user)
            if request.POST['next'] is not None:
                return redirect(request.POST['next'])
            return redirect('home')
            
        else:
            return render(request, 'accounts/login.html', {'error':'Oops! Username and Passwords Don''t match'})
    else:
        return render(request, 'accounts/login.html')
    
    
def logoutview(request):
    if request.method=='POST':
        logout(request)
        return redirect('home')
        
    

reditclone/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post

# Create your views here.
@login_required
def create(request):
    if request.method=='POST':
        if request.POST['Title'] and request.POST['Url']:
            post=Post()
            post.title= request.POST['Title']
            if request.POST['Url'].startswith('http://') or request.POST['Url'].startswith('https://'):
                post.url= request.POST['Url']
            else:
                post.url= 'http://' + request.POST['Url']
            post.pub_date = timezone.datetime.now()
            post.author= request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'ERROR, You must include a title and a URL to create a Post'})
        
    else:
        return render(request, 'posts/create.html')
    
    
    
def home(request):
    posts= Post.objects.order_by('-votes_total') 
    return render(request, 'posts/home.html', {'posts':posts})


def upvote(request, pk):
    if request.method=='POST':
        post= Post.objects.get(pk=pk)
        post.votes_total +=1
        post.save()
        return redirect('home')


def downvote(request, pk):
    if request.method=='POST':
        post= Post.objects.get(pk=pk)
        post.votes_total -=1
        post.save()
        return redirect('home')
    
    
def userposts(request, fk):
    posts= Post.objects.filter(author__id=fk).order_by('-votes_total')
    return render(request, 'posts/userposts.html', {'posts':posts})
        

reditclone/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}


<center><h1>LOGIN</h1>
    
    {%if error%}
        {{ error }}
    
    {%endif%}
    
    <br />
    <br />

<form method="Post" action="{% url 'accounts:login'%}">
    {% csrf_token %}
    
    {% if request.GET.next %}
    
    <input type="hidden" name="next" value= {{request.GET.next}} />
    
    {% endif %}
    
    Username:
    <br />
    <input type="text" name="Username" />
    <br />
    Password:
    <br />
    <input type="text" name="Password" />
    <br />
    
    <br />
    <input class="btn btn-dark" type="submit" value="Login">
</form></center>


{% endblock %}

reditclone/accounts/templates/accounts/signups.html
{% extends 'base.html' %}

{% block content %}

<center><h1>SIGN UP</h1>
    
    {%if error%}
        {{ error }}
    
    {%endif%}
    
    <br />
    <br />

<form method="Post" action="{% url 'accounts:signup'%}">
    {% csrf_token %}
    Username:
    <br />
    <input type="text" name="Username" />
    <br />
    Password:
    <br />
    <input type="text" name="Password1" />
    <br />
    Confirm Password:
    <br />
    <input type="text" name="Password2" />
    <br />
    <br />
    <input class="btn btn-dark" type="submit" value="sign Up">
</form></center>

{% endblock %}

reditclone/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

<center><h1>New Post</h1>
    
    {%if error%}
        {{ error }}
    
    {%endif%}
    
    <br />
    <br />

<form method="Post" action="{% url 'posts:create'%}">
    {% csrf_token %}
    
    
    Title:
    <br />
    <input type="text" name="Title" />
    <br />
    Url:
    <br />
    <input type="text" name="Url" />
    <br />
    
    <br />
    <input class="btn btn-dark" type="submit" value="Post">
</form></center>


{% endblock %}

reditclone/posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content %}

<h1>HomePage</h1>

<a class="btn btn-dark" href="{% url 'posts:create' %}">New Post</a>

<br/>
<br/>


{% for post in posts.all %}

<table>
    <tr>
        <td style="padding-right: 20px"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-chevron-up"></span></a><br />{{post.votes_total}} <br /><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-chevron-down"></span></a></td>
        <td><a href="{{ post.url }}">{{ post.title }}</a><br/>{{post.pub_date}} by <a href="{% url 'posts:userposts' post.author.id %}">{{post.author.username}}</a>
<br/> </td>
        
        </tr>
    </table>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
              {% csrf_token %}
              <input type="hidden">
              </form>
<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id%}">
              {% csrf_token %}
              <input type="hidden">
              </form>
{% endfor %}

{% endblock %}

reditclone/posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content %}

<h1>All posts by</h1>


<br/>
<br/>


{% for post in posts.all %}

<table>
    <tr>
        <td style="padding-right: 20px"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-chevron-up"></span></a><br />{{post.votes_total}} <br /><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-chevron-down"></span></a></td>
        <td><a href="{{ post.url }}">{{ post.title }}</a><br/>{{post.pub_date}} by <a href="{% url 'posts:userposts' post.author.id %}">{{post.author.username}}</a>
<br/> </td>
        
        </tr>
    </table>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<form id="upvote{{ post.id }}" method="POST" action="{% url 'posts:upvote' post.id %}">
              {% csrf_token %}
              <input type="hidden">
              </form>
<form id="downvote{{ post.id }}" method="POST" action="{% url 'posts:downvote' post.id%}">
              {% csrf_token %}
              <input type="hidden">
              </form>
{% endfor %}

{% endblock %}

reditclone/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Reddit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home'%}">Reddit Clone</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
 </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li><a href="#" onClick="document.getElementById('logout').submit()">Logout</a></li>
          <form id="logout" method="POST" action="{% url 'accounts:logout'%}">
              {% csrf_token %}
              <input type="hidden">
              </form>
         
           {% else %}
          <li><a href="{% url 'accounts:login'%}">Login</a></li>
          <li><a href="{% url 'accounts:signup'%}">signup</a></li>
           {% endif %}
            </ul>
          </div>
      </div>
</nav>
    
    <div class="container-fluid">      
      
    {% block content %}
    {% endblock %}
     </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>